# Generated by Django 3.2.5 on 2021-11-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=250)),
                ('first_name', models.TextField()),
                ('photo', models.URLField()),
                ('gender', models.TextField()),
                ('experience', models.IntegerField()),
                ('role', models.TextField()),
                ('company', models.TextField()),
                ('facts', models.CharField(max_length=150)),
                ('date_created', models.DateField()),
                ('linkedin', models.URLField()),
                ('status', models.TextField()),
            ],
        ),
    ]
