# Generated by Django 3.2.5 on 2021-11-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20211115_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.CharField(choices=[('not_set', 'not_set'), ('0-3', '0-3'), ('3-5', '3-5'), ('5-7', '7-10'), ('10+', '10+')], default='not_set', max_length=100),
        ),
    ]
