# Generated by Django 3.2.5 on 2021-11-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_profile_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('not_set', 'not_set'), ('Female', 'Female'), ('Non-binary', 'Non-binary')], default='not_set', max_length=50),
        ),
    ]
