# Generated by Django 3.2.5 on 2021-11-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.CharField(choices=[('not_set', 'not_set'), ('1-3', '1-3'), ('3-5', '3-5'), ('5-7', '5-7'), ('7-9', '7-9'), ('10+', '10+')], default='not_set', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('not_set', 'not_set'), ('Woman', 'Woman'), ('Non-binary', 'Non-binary')], default='not_set', max_length=50),
        ),
    ]
