# Generated by Django 3.2.5 on 2021-11-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20211117_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('not_set', 'not_set'), ('Woman', 'Woman'), ('Non-binary', 'Non-binary')], default='Pending', max_length=50),
        ),
    ]
